name: Kodi
on:
  # Run action when pushed to master, or for commits in a pull request.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  kodi-addon-checker:
    name: Addon checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v5
        with:
          path: ${{ github.repository }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/xbmc/addon-check.git
      - name: Remove unwanted files
        run: awk '/export-ignore/ { print $1 }' .gitattributes | xargs rm -rf --
      - name: Run kodi-addon-checker
        run: kodi-addon-checker --branch=matrix ${{ github.repository }}/
