name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Release plugin.video.goplay
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v5

      - name: Get changelog
        id: get-changelog
        run: |
          description=$(sed '0,/^## Changelog$/d;/## \[v[0-9\.]*/d;/^$/,$d' README.md)
          echo $description
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "body<<$EOF" >> $GITHUB_OUTPUT
          echo "$description" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Generate distribution zips
        run: scripts/build.py

      - name: Create Release on Github
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.get-changelog.outputs.body }}
          draft: false
          prerelease: false
          files: "dist/*.zip"
          token: ${{ secrets.GH_TOKEN }}

      - name: Submit release to official kodi repository
        id: submit-to-kodi-repo
        uses: mediaminister/action-kodi-addon-submitter@master
        with:
          kodi-repository: repo-plugins
          kodi-version: matrix
          addon-id: plugin.video.goplay
        env:
          GH_USERNAME: ${{secrets.GH_USERNAME}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          EMAIL: ${{secrets.EMAIL}}
